### ISSUE TITLE
Release without personally identifying info.

### ISSUE THREAD

**Issue by khrj** [LinusS1/tech-support#1]
Awesome app!
I'd want to send this to a lot of people, but most don't know Eric and Hack Club (and probably wouldn't care even if they did know). Could you make a release with a generic name and title? Thanks!

**Comment by LinusSkucas** [comment]
Sure, if you make me an app icon 🙃

**Comment by sarthaktexas** [comment]
lmao @LinusS1 i love this repo, what's the specifications for the app icons? i'll make one and send it to you.

**Comment by LinusSkucas** [comment]
Done!
